### ISSUE TITLE
where is the finetune.py?

### ISSUE THREAD

**Issue by cheershuaizhao** [sheryl-ai/MetaPred#1]
There should be an important finetune.py file according to line 11 at main.py.
>>import finetune

Could you please point to that file?

**Comment by sheryl-ai** [comment]
will release a complete version later

**Comment by cheershuaizhao** [comment]
I am mostly curious in finetune, did you use the target domain data to retrain the model? Based on your paper algorithm 2 pseduo-code, it looks like retraining with source domain S_i. typo there?

**Comment by sheryl-ai** [comment]
Thanks for your interest. Please see the detail here
https://dl.acm.org/citation.cfm?id=3330779 The finetune algorithm is pretty
much the same as the traditional fine-tune method. We only use the target
domain data in finetune. So it could be a typo.

- Xi


*Xi Sheryl Zhang, Ph.D. *
Postdoctoral Associate
Homepage: xi-zhang.net

*Cornell University*
Weill Cornell Medicine
Department of Healthcare Policy & Research
425 East 61st Street, Suite 301, New York, NY 10065

**Comment by cheershuaizhao** [comment]
I see, I looked at the old arXiv version earlier. Thanks.
